import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { listClaudeSessionsForWorkDir } from '../adapters/claudeCliAdapter';

// `listClaudeSessionsForWorkDir(projectsRoot, workDir)` reads the real
// `<projectsRoot>/<slug>/*.jsonl` Claude transcripts, keeps only those whose
// recorded cwd === workDir, and normalizes each into an `AgentSession`. We
// drive it against temp fixtures shaped like REAL Claude transcripts so the
// parser, slug resolution, cwd filter, UUID gate, summary-by-leafUuid title
// selection, and title precedence are all exercised end-to-end.
//
// Title precedence: summaryTitle ?? firstMeaningfulPrompt ?? firstUser ?? id.
// `summaryTitle` is legacy (current Claude no longer writes `summary` lines);
// the primary source is now the first MEANINGFUL prompt — preamble/marker
// stripped, tooling noise skipped (see `utils/claudeSessionTitle.ts`).
//
// Real schema (confirmed against ~/.claude/projects/*.jsonl):
//   user      → { type:'user', cwd, timestamp, uuid, message:{ role, content } }
//   summary   → { type:'summary', summary, leafUuid }  (legacy; absent in 2.1.201)
// A file can hold MANY summary entries; the one describing THIS conversation
// is the summary whose leafUuid points at a message uuid present in the file.

const validUuidA = 'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa';
const validUuidB = 'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb';
const validUuidC = 'cccccccc-cccc-4ccc-cccc-cccccccccccc';
const validUuidD = 'dddddddd-dddd-4ddd-dddd-dddddddddddd';
const validUuidE = 'eeeeeeee-eeee-4eee-eeee-eeeeeeeeeeee';

/** Claude's slug = absolute path with every non-alphanumeric char → '-'. */
function getSlug(workDir: string): string {
  return workDir.replace(/[^a-zA-Z0-9]/g, '-');
}

function writeTranscript(dir: string, fileStem: string, entries: object[]): void {
  const body = entries.map(entry => JSON.stringify(entry)).join('\n') + '\n';
  fs.writeFileSync(path.join(dir, `${fileStem}.jsonl`), body);
}

/** A real-shaped user message line with a message uuid the summary can link to. */
function userLine(cwd: string, timestamp: string, uuid: string, content: string): object {
  return { type: 'user', cwd, timestamp, uuid, message: { role: 'user', content } };
}

describe('listClaudeSessionsForWorkDir', () => {
  let projectsRoot: string;
  const workDir = '/home/user/projects/myProject';
  const otherDir = '/home/user/projects/otherProject';
  let slugDir: string;

  before(() => {
    projectsRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'claude-sessions-test-'));
    slugDir = path.join(projectsRoot, getSlug(workDir));
    fs.mkdirSync(slugDir, { recursive: true });

    // A: has a matching summary (leafUuid → a real message uuid in the file) AND
    //    a stale summary whose leafUuid is NOT in the file. Title must be the
    //    matching one, proving leafUuid selection, not "last summary wins".
    writeTranscript(slugDir, validUuidA, [
      { type: 'summary', summary: 'STALE other-conversation summary', leafUuid: 'not-in-this-file' },
      userLine(workDir, '2026-05-30T10:00:00.000Z', 'msg-a-1', 'first user line A'),
      userLine(workDir, '2026-05-30T10:05:00.000Z', 'msg-a-2', 'last user line A'),
      { type: 'summary', summary: 'Refactor the parser', leafUuid: 'msg-a-2' },
    ]);

    // B: no summary. First prompt is a real topic wrapped in the bot's
    //    `[Telegram thread context]` preamble; the LAST prompt is tooling noise
    //    (a `/effort` command echo). Title must be the STRIPPED FIRST topic —
    //    proving the picker now shows the first meaningful prompt, not the
    //    noisy last one (the reported "garbage titles" bug).
    writeTranscript(slugDir, validUuidB, [
      userLine(
        workDir,
        '2026-05-30T11:00:00.000Z',
        'msg-b-1',
        '[Telegram thread context]\nthread: -100:1 | folder: myProject\n\nfix the session picker',
      ),
      userLine(
        workDir,
        '2026-05-30T11:05:00.000Z',
        'msg-b-2',
        '<local-command-stdout>Set effort level to xhigh</local-command-stdout>',
      ),
    ]);

    // C: a single meaningful user message → title is that line.
    writeTranscript(slugDir, validUuidC, [
      userLine(workDir, '2026-05-30T12:00:00.000Z', 'msg-c-1', 'just chatting C'),
    ]);

    // E: no summary, and EVERY user turn is tooling noise (the `/effort` command
    //    caveat + its stdout, no real prompt — the shape of a bot session that
    //    only ran a slash command). Title must fall back to the bare id, NOT
    //    leak the `<local-command-…>` block (the live-data bug this fix closes).
    writeTranscript(slugDir, validUuidE, [
      userLine(
        workDir,
        '2026-05-30T12:30:00.000Z',
        'msg-e-1',
        '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.',
      ),
      userLine(
        workDir,
        '2026-05-30T12:31:00.000Z',
        'msg-e-2',
        '<local-command-stdout>Set effort level to xhigh</local-command-stdout>',
      ),
    ]);

    // D: recorded cwd points at ANOTHER folder → must be filtered OUT.
    writeTranscript(slugDir, validUuidD, [
      userLine(otherDir, '2026-05-30T13:00:00.000Z', 'msg-d-1', 'wrong folder D'),
      { type: 'summary', summary: 'Should not appear', leafUuid: 'msg-d-1' },
    ]);

    // Non-UUID filename → must be skipped even though cwd matches.
    writeTranscript(slugDir, 'not-a-uuid', [
      userLine(workDir, '2026-05-30T14:00:00.000Z', 'msg-x-1', 'bad id'),
    ]);
  });

  after(() => {
    fs.rmSync(projectsRoot, { recursive: true, force: true });
  });

  it('returns [] when the project folder does not exist', () => {
    const result = listClaudeSessionsForWorkDir(projectsRoot, '/no/such/folder/anywhere');
    assert.deepEqual(result, []);
  });

  it('keeps only transcripts whose recorded cwd matches workDir', () => {
    const result = listClaudeSessionsForWorkDir(projectsRoot, workDir);
    const ids = result.map(session => session.id).sort();
    // D (other folder) and the non-UUID file are excluded; A, B, C, E remain.
    assert.deepEqual(ids, [validUuidA, validUuidB, validUuidC, validUuidE]);
  });

  it('rejects a non-UUID filename even when its cwd matches', () => {
    const result = listClaudeSessionsForWorkDir(projectsRoot, workDir);
    assert.equal(result.some(session => session.id === 'not-a-uuid'), false);
  });

  it('picks the summary whose leafUuid matches a message in the same file', () => {
    const result = listClaudeSessionsForWorkDir(projectsRoot, workDir);
    const byId = new Map(result.map(session => [session.id, session]));
    // The stale summary (leafUuid not in file) must NOT win.
    assert.equal(byId.get(validUuidA)?.title, 'Refactor the parser');
  });

  it('uses the first MEANINGFUL prompt (preamble stripped, noisy last prompt skipped)', () => {
    const result = listClaudeSessionsForWorkDir(projectsRoot, workDir);
    const byId = new Map(result.map(session => [session.id, session]));
    // B: first prompt (preamble-wrapped) wins over the noisy `/effort` last prompt.
    assert.equal(byId.get(validUuidB)?.title, 'fix the session picker');
    assert.equal(byId.get(validUuidC)?.title, 'just chatting C'); // single user line
  });

  it('falls back to the bare id when no prompt is meaningful (all noise)', () => {
    const result = listClaudeSessionsForWorkDir(projectsRoot, workDir);
    const byId = new Map(result.map(session => [session.id, session]));
    // E's only turns are `/effort` caveat + stdout → no topic → title is the id.
    assert.equal(byId.get(validUuidE)?.title, validUuidE);
  });

  it('sets createdAt from the first transcript timestamp', () => {
    const result = listClaudeSessionsForWorkDir(projectsRoot, workDir);
    const sessionA = result.find(session => session.id === validUuidA);
    assert.ok(sessionA);
    assert.equal(sessionA.createdAt.toISOString(), '2026-05-30T10:00:00.000Z');
  });

  it('orders results newest-first by file mtime', () => {
    // Stamp deterministic, increasing mtimes: E oldest → A newest.
    const baseMs = Date.parse('2026-05-30T00:00:00.000Z');
    const minute = 60_000;
    const stampMtime = (fileStem: string, minutesFromBase: number): void => {
      const when = new Date(baseMs + minutesFromBase * minute);
      fs.utimesSync(path.join(slugDir, `${fileStem}.jsonl`), when, when);
    };
    stampMtime(validUuidE, 1);
    stampMtime(validUuidC, 2);
    stampMtime(validUuidB, 3);
    stampMtime(validUuidA, 4);

    const result = listClaudeSessionsForWorkDir(projectsRoot, workDir);
    assert.deepEqual(result.map(session => session.id), [
      validUuidA,
      validUuidB,
      validUuidC,
      validUuidE,
    ]);
  });
});
