/**
 * @description Unit tests for the pure Claude session-title deriver
 * (`utils/claudeSessionTitle.ts`) — the source of the `/sessions` picker title
 * now that current Claude Code no longer writes `type:"summary"` lines.
 *
 * Load-bearing intent (per `.claude/rules/tests.md`): the deriver must return
 * the session's real TOPIC, which means (a) stripping the bot's service
 * wrappers (`[Telegram thread context]` preamble, `[Scheduled run "…"]` marker)
 * off the FRONT of the prompt, and (b) rejecting tooling-noise prompts
 * (command echoes, task-notifications, bare `yes`/`commit`/`...`) so the picker
 * never shows them as a title. Each case pins a distinct wrapper/noise class,
 * not just "non-null".
 *
 * Test case: n/a (no Jira tracker for this project).
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  getSessionTitleLine,
  getSessionTitleCandidate,
} from '../utils/claudeSessionTitle';

describe('getSessionTitleLine — strip service wrappers, collapse to one line', () => {
  it('strips the [Telegram thread context] preamble, keeps the real prompt', () => {
    const raw =
      '[Telegram thread context]\ngroup: "ExampleGroup"\nthread: -100:434 | folder: telegramCode\n\nрефактори session picker';
    assert.equal(getSessionTitleLine(raw), 'рефактори session picker');
  });

  it('strips a [Scheduled run "…"] marker', () => {
    assert.equal(
      getSessionTitleLine('[Scheduled run "Nightly build"]\nrun the nightly build'),
      'run the nightly build',
    );
  });

  it('strips the preamble even when a scheduled marker is nested inside it', () => {
    const raw =
      '[Telegram thread context]\nthread: -100:434 | folder: x\n\n[Scheduled run "Job"]\ndo the thing';
    assert.equal(getSessionTitleLine(raw), 'do the thing');
  });

  it('collapses internal whitespace/newlines to single spaces', () => {
    assert.equal(getSessionTitleLine('fix   the\n\n  bug   now'), 'fix the bug now');
  });

  it('leaves a plain prompt untouched (bar trimming)', () => {
    assert.equal(getSessionTitleLine('  add /terminal command  '), 'add /terminal command');
  });
});

describe('getSessionTitleCandidate — reject tooling noise, return the topic', () => {
  it('returns the real topic from a preamble-wrapped first prompt', () => {
    const raw =
      '[Telegram thread context]\ngroup: "G"\nthread: -100:1 | folder: f\n\nпосмотри тред и почини баг';
    assert.equal(getSessionTitleCandidate(raw), 'посмотри тред и почини баг');
  });

  for (const noise of [
    '<local-command-stdout>Set effort level to xhigh (saved as your default)</local-command-stdout>',
    '<local-command-stdout>Login successful</local-command-stdout>',
    '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.',
    '<task-notification>\n<task-id>abc123</task-id>\n<output>done</output>',
    '<command-name>/effort</command-name>',
    '<system-reminder>be careful</system-reminder>',
    '[Request interrupted by user]',
    '[Request interrupted by user for tool use]',
    '[Telegram file] photo saved to: /x/y.png (12 KB)',
    '[Telegram album] 3 files saved',
    'Base directory for this skill: /home/user/src/telegramCode/.claude',
    'Set effort level to xhigh', // wrapper-less command echo
    'Set model to Fable 5',
  ]) {
    it(`rejects tooling noise: ${noise.slice(0, 34)}…`, () => {
      assert.equal(getSessionTitleCandidate(noise), null);
    });
  }

  for (const chatter of ['...', '..', '.', 'yes', 'commit', 'да, давай.', 'push', 'обнови my']) {
    it(`rejects bare chatter: ${JSON.stringify(chatter)}`, () => {
      assert.equal(getSessionTitleCandidate(chatter), null);
    });
  }

  it('rejects a preamble with no prompt after it (empty topic)', () => {
    assert.equal(getSessionTitleCandidate('[Telegram thread context]\nthread: -100:1 | folder: f'), null);
  });

  it('rejects an empty / whitespace-only prompt', () => {
    assert.equal(getSessionTitleCandidate('   \n  '), null);
  });

  it('keeps a short but real prompt that is NOT in the noise set', () => {
    assert.equal(getSessionTitleCandidate('commit plan'), 'commit plan');
    assert.equal(getSessionTitleCandidate('hi'), 'hi');
  });

  it('noise word as a PREFIX of a real sentence is kept (only exact matches are noise)', () => {
    assert.equal(
      getSessionTitleCandidate('yes, and also refactor the session picker'),
      'yes, and also refactor the session picker',
    );
  });
});
